[env:esp32-s3-devkitc-1]
platform = espressif32@6.3.2
board = esp32-s3-devkitc-1
framework = arduino

; 16MB Flash (qio) 和 8MB PSRAM (opi)
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_build.partitions = partitions.csv

monitor_speed = 115200

build_flags = 
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DBOARD_HAS_PSRAM
	-D LV_CONF_INCLUDE_SIMPLE
	-I include
	-finput-charset=UTF-8

lib_deps = 
	moononournation/GFX Library for Arduino @ 1.4.7
	lvgl/lvgl @ 8.4.0
